ep4_path="EP4"
requirements = "./requirements.txt"
schema_file="download/schema.json"
eradication_path="download/Eradication"
assets_input_dir="Assets"
plugins_folder="download"
reporters="download/reporter_plugins"
sif="dtk_centos.id"
